/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as StoreIndexImport } from './routes/Store/index'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as StoreAuthenticatedImport } from './routes/Store/_authenticated'
import { Route as ExpensesTrackerAuthenticatedImport } from './routes/ExpensesTracker/_authenticated'
import { Route as ExpensesTrackerAuthenticatedIndexImport } from './routes/ExpensesTracker/_authenticated/index'
import { Route as StoreAuthenticatedEditProductImport } from './routes/Store/_authenticated/editProduct'
import { Route as StoreAuthenticatedCreateProductImport } from './routes/Store/_authenticated/createProduct'
import { Route as StoreAuthenticatedCartImport } from './routes/Store/_authenticated/cart'
import { Route as ExpensesTrackerAuthenticatedExpensesImport } from './routes/ExpensesTracker/_authenticated/expenses'
import { Route as ExpensesTrackerAuthenticatedCreateExpenseImport } from './routes/ExpensesTracker/_authenticated/createExpense'

// Create Virtual Routes

const StoreImport = createFileRoute('/Store')()
const ExpensesTrackerImport = createFileRoute('/ExpensesTracker')()

// Create/Update Routes

const StoreRoute = StoreImport.update({
  id: '/Store',
  path: '/Store',
  getParentRoute: () => rootRoute,
} as any)

const ExpensesTrackerRoute = ExpensesTrackerImport.update({
  id: '/ExpensesTracker',
  path: '/ExpensesTracker',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StoreIndexRoute = StoreIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const StoreAuthenticatedRoute = StoreAuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => StoreRoute,
} as any)

const ExpensesTrackerAuthenticatedRoute =
  ExpensesTrackerAuthenticatedImport.update({
    id: '/_authenticated',
    getParentRoute: () => ExpensesTrackerRoute,
  } as any)

const ExpensesTrackerAuthenticatedIndexRoute =
  ExpensesTrackerAuthenticatedIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ExpensesTrackerAuthenticatedRoute,
  } as any)

const StoreAuthenticatedEditProductRoute =
  StoreAuthenticatedEditProductImport.update({
    id: '/editProduct',
    path: '/editProduct',
    getParentRoute: () => StoreAuthenticatedRoute,
  } as any)

const StoreAuthenticatedCreateProductRoute =
  StoreAuthenticatedCreateProductImport.update({
    id: '/createProduct',
    path: '/createProduct',
    getParentRoute: () => StoreAuthenticatedRoute,
  } as any)

const StoreAuthenticatedCartRoute = StoreAuthenticatedCartImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StoreAuthenticatedRoute,
} as any)

const ExpensesTrackerAuthenticatedExpensesRoute =
  ExpensesTrackerAuthenticatedExpensesImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => ExpensesTrackerAuthenticatedRoute,
  } as any)

const ExpensesTrackerAuthenticatedCreateExpenseRoute =
  ExpensesTrackerAuthenticatedCreateExpenseImport.update({
    id: '/createExpense',
    path: '/createExpense',
    getParentRoute: () => ExpensesTrackerAuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/ExpensesTracker': {
      id: '/ExpensesTracker'
      path: '/ExpensesTracker'
      fullPath: '/ExpensesTracker'
      preLoaderRoute: typeof ExpensesTrackerImport
      parentRoute: typeof rootRoute
    }
    '/ExpensesTracker/_authenticated': {
      id: '/ExpensesTracker/_authenticated'
      path: '/ExpensesTracker'
      fullPath: '/ExpensesTracker'
      preLoaderRoute: typeof ExpensesTrackerAuthenticatedImport
      parentRoute: typeof ExpensesTrackerRoute
    }
    '/Store': {
      id: '/Store'
      path: '/Store'
      fullPath: '/Store'
      preLoaderRoute: typeof StoreImport
      parentRoute: typeof rootRoute
    }
    '/Store/_authenticated': {
      id: '/Store/_authenticated'
      path: '/Store'
      fullPath: '/Store'
      preLoaderRoute: typeof StoreAuthenticatedImport
      parentRoute: typeof StoreRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/Store/': {
      id: '/Store/'
      path: '/'
      fullPath: '/Store/'
      preLoaderRoute: typeof StoreIndexImport
      parentRoute: typeof StoreImport
    }
    '/ExpensesTracker/_authenticated/createExpense': {
      id: '/ExpensesTracker/_authenticated/createExpense'
      path: '/createExpense'
      fullPath: '/ExpensesTracker/createExpense'
      preLoaderRoute: typeof ExpensesTrackerAuthenticatedCreateExpenseImport
      parentRoute: typeof ExpensesTrackerAuthenticatedImport
    }
    '/ExpensesTracker/_authenticated/expenses': {
      id: '/ExpensesTracker/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/ExpensesTracker/expenses'
      preLoaderRoute: typeof ExpensesTrackerAuthenticatedExpensesImport
      parentRoute: typeof ExpensesTrackerAuthenticatedImport
    }
    '/Store/_authenticated/cart': {
      id: '/Store/_authenticated/cart'
      path: '/cart'
      fullPath: '/Store/cart'
      preLoaderRoute: typeof StoreAuthenticatedCartImport
      parentRoute: typeof StoreAuthenticatedImport
    }
    '/Store/_authenticated/createProduct': {
      id: '/Store/_authenticated/createProduct'
      path: '/createProduct'
      fullPath: '/Store/createProduct'
      preLoaderRoute: typeof StoreAuthenticatedCreateProductImport
      parentRoute: typeof StoreAuthenticatedImport
    }
    '/Store/_authenticated/editProduct': {
      id: '/Store/_authenticated/editProduct'
      path: '/editProduct'
      fullPath: '/Store/editProduct'
      preLoaderRoute: typeof StoreAuthenticatedEditProductImport
      parentRoute: typeof StoreAuthenticatedImport
    }
    '/ExpensesTracker/_authenticated/': {
      id: '/ExpensesTracker/_authenticated/'
      path: '/'
      fullPath: '/ExpensesTracker/'
      preLoaderRoute: typeof ExpensesTrackerAuthenticatedIndexImport
      parentRoute: typeof ExpensesTrackerAuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ExpensesTrackerAuthenticatedRouteChildren {
  ExpensesTrackerAuthenticatedCreateExpenseRoute: typeof ExpensesTrackerAuthenticatedCreateExpenseRoute
  ExpensesTrackerAuthenticatedExpensesRoute: typeof ExpensesTrackerAuthenticatedExpensesRoute
  ExpensesTrackerAuthenticatedIndexRoute: typeof ExpensesTrackerAuthenticatedIndexRoute
}

const ExpensesTrackerAuthenticatedRouteChildren: ExpensesTrackerAuthenticatedRouteChildren =
  {
    ExpensesTrackerAuthenticatedCreateExpenseRoute:
      ExpensesTrackerAuthenticatedCreateExpenseRoute,
    ExpensesTrackerAuthenticatedExpensesRoute:
      ExpensesTrackerAuthenticatedExpensesRoute,
    ExpensesTrackerAuthenticatedIndexRoute:
      ExpensesTrackerAuthenticatedIndexRoute,
  }

const ExpensesTrackerAuthenticatedRouteWithChildren =
  ExpensesTrackerAuthenticatedRoute._addFileChildren(
    ExpensesTrackerAuthenticatedRouteChildren,
  )

interface ExpensesTrackerRouteChildren {
  ExpensesTrackerAuthenticatedRoute: typeof ExpensesTrackerAuthenticatedRouteWithChildren
}

const ExpensesTrackerRouteChildren: ExpensesTrackerRouteChildren = {
  ExpensesTrackerAuthenticatedRoute:
    ExpensesTrackerAuthenticatedRouteWithChildren,
}

const ExpensesTrackerRouteWithChildren = ExpensesTrackerRoute._addFileChildren(
  ExpensesTrackerRouteChildren,
)

interface StoreAuthenticatedRouteChildren {
  StoreAuthenticatedCartRoute: typeof StoreAuthenticatedCartRoute
  StoreAuthenticatedCreateProductRoute: typeof StoreAuthenticatedCreateProductRoute
  StoreAuthenticatedEditProductRoute: typeof StoreAuthenticatedEditProductRoute
}

const StoreAuthenticatedRouteChildren: StoreAuthenticatedRouteChildren = {
  StoreAuthenticatedCartRoute: StoreAuthenticatedCartRoute,
  StoreAuthenticatedCreateProductRoute: StoreAuthenticatedCreateProductRoute,
  StoreAuthenticatedEditProductRoute: StoreAuthenticatedEditProductRoute,
}

const StoreAuthenticatedRouteWithChildren =
  StoreAuthenticatedRoute._addFileChildren(StoreAuthenticatedRouteChildren)

interface StoreRouteChildren {
  StoreAuthenticatedRoute: typeof StoreAuthenticatedRouteWithChildren
  StoreIndexRoute: typeof StoreIndexRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreAuthenticatedRoute: StoreAuthenticatedRouteWithChildren,
  StoreIndexRoute: StoreIndexRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/ExpensesTracker': typeof ExpensesTrackerAuthenticatedRouteWithChildren
  '/Store': typeof StoreAuthenticatedRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/Store/': typeof StoreIndexRoute
  '/ExpensesTracker/createExpense': typeof ExpensesTrackerAuthenticatedCreateExpenseRoute
  '/ExpensesTracker/expenses': typeof ExpensesTrackerAuthenticatedExpensesRoute
  '/Store/cart': typeof StoreAuthenticatedCartRoute
  '/Store/createProduct': typeof StoreAuthenticatedCreateProductRoute
  '/Store/editProduct': typeof StoreAuthenticatedEditProductRoute
  '/ExpensesTracker/': typeof ExpensesTrackerAuthenticatedIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/ExpensesTracker': typeof ExpensesTrackerAuthenticatedIndexRoute
  '/Store': typeof StoreIndexRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/ExpensesTracker/createExpense': typeof ExpensesTrackerAuthenticatedCreateExpenseRoute
  '/ExpensesTracker/expenses': typeof ExpensesTrackerAuthenticatedExpensesRoute
  '/Store/cart': typeof StoreAuthenticatedCartRoute
  '/Store/createProduct': typeof StoreAuthenticatedCreateProductRoute
  '/Store/editProduct': typeof StoreAuthenticatedEditProductRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/ExpensesTracker': typeof ExpensesTrackerRouteWithChildren
  '/ExpensesTracker/_authenticated': typeof ExpensesTrackerAuthenticatedRouteWithChildren
  '/Store': typeof StoreRouteWithChildren
  '/Store/_authenticated': typeof StoreAuthenticatedRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/Store/': typeof StoreIndexRoute
  '/ExpensesTracker/_authenticated/createExpense': typeof ExpensesTrackerAuthenticatedCreateExpenseRoute
  '/ExpensesTracker/_authenticated/expenses': typeof ExpensesTrackerAuthenticatedExpensesRoute
  '/Store/_authenticated/cart': typeof StoreAuthenticatedCartRoute
  '/Store/_authenticated/createProduct': typeof StoreAuthenticatedCreateProductRoute
  '/Store/_authenticated/editProduct': typeof StoreAuthenticatedEditProductRoute
  '/ExpensesTracker/_authenticated/': typeof ExpensesTrackerAuthenticatedIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/ExpensesTracker'
    | '/Store'
    | '/profile'
    | '/Store/'
    | '/ExpensesTracker/createExpense'
    | '/ExpensesTracker/expenses'
    | '/Store/cart'
    | '/Store/createProduct'
    | '/Store/editProduct'
    | '/ExpensesTracker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/ExpensesTracker'
    | '/Store'
    | '/profile'
    | '/ExpensesTracker/createExpense'
    | '/ExpensesTracker/expenses'
    | '/Store/cart'
    | '/Store/createProduct'
    | '/Store/editProduct'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/ExpensesTracker'
    | '/ExpensesTracker/_authenticated'
    | '/Store'
    | '/Store/_authenticated'
    | '/_authenticated/profile'
    | '/Store/'
    | '/ExpensesTracker/_authenticated/createExpense'
    | '/ExpensesTracker/_authenticated/expenses'
    | '/Store/_authenticated/cart'
    | '/Store/_authenticated/createProduct'
    | '/Store/_authenticated/editProduct'
    | '/ExpensesTracker/_authenticated/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ExpensesTrackerRoute: typeof ExpensesTrackerRouteWithChildren
  StoreRoute: typeof StoreRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ExpensesTrackerRoute: ExpensesTrackerRouteWithChildren,
  StoreRoute: StoreRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/about",
        "/ExpensesTracker",
        "/Store"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/profile"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/ExpensesTracker": {
      "filePath": "ExpensesTracker",
      "children": [
        "/ExpensesTracker/_authenticated"
      ]
    },
    "/ExpensesTracker/_authenticated": {
      "filePath": "ExpensesTracker/_authenticated.tsx",
      "parent": "/ExpensesTracker",
      "children": [
        "/ExpensesTracker/_authenticated/createExpense",
        "/ExpensesTracker/_authenticated/expenses",
        "/ExpensesTracker/_authenticated/"
      ]
    },
    "/Store": {
      "filePath": "Store",
      "children": [
        "/Store/_authenticated",
        "/Store/"
      ]
    },
    "/Store/_authenticated": {
      "filePath": "Store/_authenticated.tsx",
      "parent": "/Store",
      "children": [
        "/Store/_authenticated/cart",
        "/Store/_authenticated/createProduct",
        "/Store/_authenticated/editProduct"
      ]
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated"
    },
    "/Store/": {
      "filePath": "Store/index.tsx",
      "parent": "/Store"
    },
    "/ExpensesTracker/_authenticated/createExpense": {
      "filePath": "ExpensesTracker/_authenticated/createExpense.tsx",
      "parent": "/ExpensesTracker/_authenticated"
    },
    "/ExpensesTracker/_authenticated/expenses": {
      "filePath": "ExpensesTracker/_authenticated/expenses.tsx",
      "parent": "/ExpensesTracker/_authenticated"
    },
    "/Store/_authenticated/cart": {
      "filePath": "Store/_authenticated/cart.tsx",
      "parent": "/Store/_authenticated"
    },
    "/Store/_authenticated/createProduct": {
      "filePath": "Store/_authenticated/createProduct.tsx",
      "parent": "/Store/_authenticated"
    },
    "/Store/_authenticated/editProduct": {
      "filePath": "Store/_authenticated/editProduct.tsx",
      "parent": "/Store/_authenticated"
    },
    "/ExpensesTracker/_authenticated/": {
      "filePath": "ExpensesTracker/_authenticated/index.tsx",
      "parent": "/ExpensesTracker/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
